name: cdt_amsterdam2025
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - tqdm
  - cobyqa
  - matplotlib
  - jupyter
  - sobol_seq
  - plotly
  - gpytorch
  - rdkit
  - sklearn
  - torch
